version: '2.1'

services:
  wildfly:
    image: 'docker.io/bitnami/wildfly:16.0.0-r66'
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - 'wildfly_data:/bitnami'
    environment:
      - WILDFLY_PASSWORD=password
      - WILDFLY_HOME/modules
volumes:
  wildfly_data:
    driver: local
